import Foundation

// Keep in sync with src/utils/glyphs.ts — any new GlyphKey added there must
// also be mapped here, otherwise widget tasks using that glyph fall back to
// the default house icon.

func sfSymbol(forGlyph key: String) -> String {
    switch key {
    case "car": return "car.fill"
    case "bed": return "bed.double.fill"
    case "toilet": return "toilet.fill"
    case "kitchen": return "fork.knife"
    case "entry": return "house.fill"
    case "dish": return "dishwasher.fill"
    case "car_tax": return "creditcard.fill"
    case "pill": return "pills.fill"
    case "plant": return "leaf.fill"
    case "workout": return "figure.strengthtraining.traditional"
    case "trash": return "trash.fill"
    case "mail": return "envelope.fill"
    case "phone": return "phone.fill"
    case "filter": return "line.3.horizontal.decrease"
    case "heart": return "heart.fill"
    case "star": return "star.fill"
    case "book": return "book.fill"
    case "note": return "note.text"
    case "shopping": return "bag.fill"
    case "dumbbell": return "dumbbell.fill"
    case "run": return "figure.run"
    case "water": return "drop.fill"
    case "bath": return "bathtub.fill"
    case "candle": return "flame.fill"
    case "leaf": return "leaf.fill"
    case "tree": return "tree.fill"
    case "pet": return "pawprint.fill"
    case "bike": return "bicycle"
    case "music": return "music.note"
    case "gift": return "gift.fill"
    case "lock": return "lock.fill"
    case "globe": return "globe"
    case "briefcase": return "briefcase.fill"
    case "droplet": return "drop.fill"
    case "sun": return "sun.max.fill"
    case "snow": return "snowflake"
    case "fire": return "flame.fill"
    case "clock": return "clock.fill"
    case "wallet": return "wallet.bifold.fill"
    case "card": return "creditcard.fill"
    case "gear": return "gearshape.fill"
    case "tools": return "wrench.and.screwdriver.fill"
    case "sofa": return "sofa.fill"
    case "chair": return "chair.fill"
    case "lamp": return "lamp.desk.fill"
    case "shower": return "shower.fill"
    case "washer": return "washer.fill"
    case "dryer": return "dryer.fill"
    case "oven": return "oven.fill"
    case "microwave": return "microwave.fill"
    case "fridge": return "refrigerator.fill"
    case "coffee": return "cup.and.saucer.fill"
    case "wine": return "wineglass.fill"
    case "carrot": return "carrot.fill"
    case "airplane": return "airplane"
    case "bus": return "bus.fill"
    case "fuel": return "fuelpump.fill"
    case "laptop": return "laptopcomputer"
    case "printer": return "printer.fill"
    case "camera": return "camera.fill"
    case "folder": return "folder.fill"
    case "doc": return "doc.text.fill"
    case "message": return "message.fill"
    case "bell": return "bell.fill"
    case "calendar": return "calendar"
    case "alarm": return "alarm.fill"
    case "cart": return "cart.fill"
    case "dollar": return "dollarsign.circle.fill"
    case "walk": return "figure.walk"
    case "hiking": return "figure.hiking"
    case "stethoscope": return "stethoscope"
    case "dog": return "dog.fill"
    case "cat": return "cat.fill"
    case "bird": return "bird.fill"
    case "fish": return "fish.fill"
    case "cloud": return "cloud.fill"
    case "rain": return "cloud.rain.fill"
    case "moon": return "moon.fill"
    case "bolt": return "bolt.fill"
    case "headphones": return "headphones"
    case "guitar": return "guitars.fill"
    case "books": return "books.vertical.fill"
    case "graduation": return "graduationcap.fill"
    case "bookmark": return "bookmark.fill"
    case "flag": return "flag.fill"
    case "tag": return "tag.fill"
    case "key": return "key.fill"
    case "scissors": return "scissors"
    default: return "house.fill"
    }
}
