import Foundation

func sfSymbol(forGlyph key: String) -> String {
    switch key {
    case "car": return "car.fill"
    case "bed": return "bed.double.fill"
    case "toilet": return "toilet.fill"
    case "kitchen": return "fork.knife"
    case "entry": return "house.fill"
    case "dish": return "dishwasher.fill"
    case "car_tax": return "creditcard.fill"
    case "pill": return "pills.fill"
    case "plant": return "leaf.fill"
    case "workout": return "figure.strengthtraining.traditional"
    case "trash": return "trash.fill"
    case "mail": return "envelope.fill"
    case "phone": return "phone.fill"
    case "filter": return "line.3.horizontal.decrease"
    case "heart": return "heart.fill"
    case "star": return "star.fill"
    case "book": return "book.fill"
    case "note": return "note.text"
    case "shopping": return "bag.fill"
    case "dumbbell": return "dumbbell.fill"
    case "run": return "figure.run"
    case "water": return "drop.fill"
    case "bath": return "bathtub.fill"
    case "candle": return "flame.fill"
    case "leaf": return "leaf.fill"
    case "tree": return "tree.fill"
    case "pet": return "pawprint.fill"
    case "bike": return "bicycle"
    case "music": return "music.note"
    case "gift": return "gift.fill"
    case "lock": return "lock.fill"
    case "globe": return "globe"
    case "briefcase": return "briefcase.fill"
    case "droplet": return "drop.fill"
    case "sun": return "sun.max.fill"
    case "snow": return "snowflake"
    case "fire": return "flame.fill"
    case "clock": return "clock.fill"
    case "wallet": return "wallet.bifold.fill"
    case "card": return "creditcard.fill"
    case "gear": return "gearshape.fill"
    case "tools": return "wrench.and.screwdriver.fill"
    default: return "house.fill"
    }
}
